import json
import os

# Define absolute paths
locales_dir = r"c:\Users\Rohan R\Documents\Google Hackathon 2026\Frontend\src\locales"

new_keys_en = {
    "labels": {
        "dry": "Dry",
        "decreasing": "Decreasing",
        "locale": "Locale",
        "farms": "farms"
    },
    "buttons": {
        "stopAudio": "Stop Audio",
        "listenTts": "Listen (TTS)",
        "logAction": "Log Action",
        "dismiss": "Dismiss",
        "markComplete": "Mark Complete",
        "logOutcome": "Log Outcome & Close"
    },
    "states": {
        "thinking": "Thinking..."
    },
    "simulator": {
        "soilType": "Soil type",
        "soilClayLoam": "Clay Loam (Vertisol)",
        "soilSiltLoam": "Silt Loam",
        "soilSandyLoam": "Sandy Loam",
        "rotationLabel": "3-year crop rotation",
        "selectCrop": "Select crop...",
        "cropWheat": "Wheat (Indo-Gangetic Plain)",
        "cropRice": "Rice Paddy (Water intensive)",
        "cropCotton": "Cotton (Deccan rainfed)",
        "cropSoybean": "Soybean (Legume nitrogen fixer)",
        "cropSunnhemp": "Sunn Hemp (Cover crop)",
        "cropCowpea": "Cowpea (Cover crop)",
        "disclaimer": "Calculations are deterministic based on agronomic inputs, while strategies are generated by Gemini.",
        "resultsTitle": "Simulation results",
        "noSimulation": "No simulation yet",
        "runPrompt": "Enter your parameters and run the simulation to see projected outcomes.",
        "runningSimulation": "Running multi-scenario simulation...",
        "creditsYr": "Credits/yr",
        "chartTitle": "Scenario {selectedScenario} Details: SOC & Credit Accrual Trend (2026-2030)",
        "soilCarbon": "Soil Carbon (%)",
        "agroAnalysis": "AI Strategic Agro-rotation Analysis",
        "errorSoil": "Select a soil type",
        "errorAcreage": "Enter acreage greater than 0",
        "errorAcreageLarge": "Value too large",
        "errorYield": "Enter a valid yield",
        "errorRotation": "Select a crop for each year"
    },
    "copilot": {
        "consoleTitle": "AI Reasoning Console",
        "defaultInferred": "The cotton plants are experiencing moderate water stress during the crucial flowering period, which is causing vegetative density to decrease.",
        "defaultRec1": "Run a 12mm irrigation cycle in West Field.",
        "defaultRec2": "Consider Alternate Wetting and Drying (AWD) to strengthen root resilience.",
        "defaultRec3": "Spray organic shield (Pseudomonas fluorescens) if humidity increases.",
        "groundingTitle": "Active Grounding Context",
        "groundingSubtitle": "This context is automatically injected into Gemini's prompt to keep responses grounded in your farm's live telemetry.",
        "sampleInquiries": "Sample Inquiries:",
        "sampleInquiry1": "\"Why is my cotton NDVI dropping? What irrigation steps do I need?\"",
        "sampleInquiry2": "\"What Bt cotton practices prevent Pink Bollworm in Maharashtra?\"",
        "sampleInquiry3": "\"How can I break soil compaction in my clay Vertisol soil?\""
    },
    "actions": {
        "addCustom": "Add Custom Action",
        "emptyTitle": "No actions found",
        "emptySubtitle": "Select another filter or add a custom agronomic action to get started.",
        "dueDateLabel": "Due Date",
        "descriptionLabel": "Recommendation / Action Description",
        "fieldSelector": "Field Selector",
        "feedbackLoopTitle": "Decision Feedback Loop",
        "feedbackInstructions": "To complete this action, please record the physical outcomes. This provides auditability and helps Gemini improve future recommendations.",
        "outcomeLabel": "Observed Outcome / Action Report",
        "observationsLabel": "Subsequent Visual Observations"
    },
    "indiaIntel": {
        "title": "India Agricultural Intelligence",
        "subtitle": "National and regional data aggregation. Monitor crop health trends, cooperative water stress warnings, and lookup verified ICAR guidelines.",
        "stateLabel": "State / Region",
        "districtLabel": "District",
        "cropSpecLabel": "Crop Spec",
        "seasonLabel": "Season",
        "activeConnections": "Active Node Connections",
        "regionalPool": "Regional Pool",
        "cropWaterStress": "Crop Water Stress",
        "groundwaterDepleting": "Monitored groundwater depleting",
        "adoptionRate": "Regenerative Adoption Rate",
        "adoptionDetails": "Cover crop & AWD adoption",
        "coopAlerts": "Cooperative Community Alerts",
        "coopAlertsSub": "Shared insights between regional nodes. Cooperatively alerts neighbors on pest outbreaks or groundwater over-draws.",
        "noAlerts": "No alerts reported in this region.",
        "ragTitle": "Authoritative ICAR Knowledge RAG",
        "ragSubtitle": "Search verified guidelines from the Indian Council of Agricultural Research. Returns context-anchored regenerative practices.",
        "ragPlaceholder": "e.g. Sowing window for wheat, alternate wetting and drying",
        "verifiedGuideline": "Verified Guideline",
        "askQuestion": "Ask a question",
        "ragPrompt": "Retrieve regional practices for India-scale wheat, rice, or cotton."
    }
}

new_keys_hi = {
    "labels": {
        "dry": "सूखा",
        "decreasing": "घट रहा है",
        "locale": "स्थान",
        "farms": "खेत"
    },
    "buttons": {
        "stopAudio": "ऑडियो रोकें",
        "listenTts": "सुनें (TTS)",
        "logAction": "कार्रवाई लॉग करें",
        "dismiss": "खारिज करें",
        "markComplete": "पूर्ण चिह्नित करें",
        "logOutcome": "परिणाम लॉग करें और बंद करें"
    },
    "states": {
        "thinking": "सोच रहा हूँ..."
    },
    "simulator": {
        "soilType": "मिट्टी का प्रकार",
        "soilClayLoam": "चिकनी दोमट (वर्टिसोल)",
        "soilSiltLoam": "गाद दोमट (सिल्ट लोम)",
        "soilSandyLoam": "बलुई दोमट (सैंडी लोम)",
        "rotationLabel": "3-वर्षीय फसल चक्र",
        "selectCrop": "फसल चुनें...",
        "cropWheat": "गेहूं (भारत-गंगा का मैदान)",
        "cropRice": "धान (पानी गहन)",
        "cropCotton": "कपास (दक्कन वर्षा आधारित)",
        "cropSoybean": "सोयाबीन (लेग्यूम नाइट्रोजन फिक्सर)",
        "cropSunnhemp": "सन हेम्प (हरी खाद फसल)",
        "cropCowpea": "लोबिया (हरी खाद फसल)",
        "disclaimer": "गणना कृषि इनपुट के आधार पर निर्धारित है, जबकि रणनीतियाँ मिथुन (Gemini) द्वारा उत्पन्न की जाती हैं।",
        "resultsTitle": "सिमुलेशन परिणाम",
        "noSimulation": "अभी तक कोई सिमुलेशन नहीं",
        "runPrompt": "अपने पैरामीटर दर्ज करें और अनुमानित परिणाम देखने के लिए सिमुलेशन चलाएं।",
        "runningSimulation": "बहु-परिदृश्य सिमुलेशन चल रहा है...",
        "creditsYr": "क्रेडिट/वर्ष",
        "chartTitle": "परिदृश्य {selectedScenario} विवरण: एसओसी और क्रेडिट संचय रुझान (2026-2030)",
        "soilCarbon": "मिट्टी कार्बन (%)",
        "agroAnalysis": "एआई रणनीतिक कृषि-चक्र विश्लेषण",
        "errorSoil": "मिट्टी का प्रकार चुनें",
        "errorAcreage": "0 से अधिक रकबा दर्ज करें",
        "errorAcreageLarge": "मूल्य बहुत बड़ा है",
        "errorYield": "एक मान्य उपज दर्ज करें",
        "errorRotation": "प्रत्येक वर्ष के लिए एक फसल चुनें"
    },
    "copilot": {
        "consoleTitle": "एआई रीजनिंग कंसोल",
        "defaultInferred": "कपास के पौधे महत्वपूर्ण फूल आने की अवधि के दौरान मध्यम पानी के तनाव का सामना कर रहे हैं, जिससे वनस्पति घनत्व कम हो रहा है।",
        "defaultRec1": "पश्चिम खेत में 12 मिमी सिंचाई चक्र चलाएं।",
        "defaultRec2": "जड़ों के लचीलेपन को मजबूत करने के लिए वैकल्पिक गीलापन और सुखाने (AWD) पर विचार करें।",
        "defaultRec3": "यदि आर्द्रता बढ़ती है तो जैविक शील्ड (स्यूडोमोनास फ्लोरेसेंस) का छिड़काव करें।",
        "groundingTitle": "सक्रिय ग्राउंडिंग संदर्भ",
        "groundingSubtitle": "प्रतिक्रियाओं को आपके खेत के लाइव टेलीमेट्री में ग्राउंड रखने के लिए यह संदर्भ स्वचालित रूप से मिथुन (Gemini) के प्रॉम्प्ट में इंजेक्ट किया जाता है।",
        "sampleInquiries": "नमूना पूछताछ:",
        "sampleInquiry1": "\"मेरा कपास एनडीवीआई क्यों गिर रहा है? मुझे सिंचाई के किन कदमों की आवश्यकता है?\"",
        "sampleInquiry2": "\"महाराष्ट्र में पिंक बोलवर्म को रोकने के लिए कौन से बीटी कपास अभ्यास हैं?\"",
        "sampleInquiry3": "\"मैं अपनी चिकनी वर्टिसोल मिट्टी में मिट्टी के संघनन को कैसे तोड़ सकता हूँ?\""
    },
    "actions": {
        "addCustom": "कस्टम कार्य जोड़ें",
        "emptyTitle": "कोई कार्रवाई नहीं मिली",
        "emptySubtitle": "शुरू करने के लिए दूसरा फ़िल्टर चुनें या कोई कस्टम कृषि कार्य जोड़ें।",
        "dueDateLabel": "नियत तारीख",
        "descriptionLabel": "सिफारिश / कार्रवाई विवरण",
        "fieldSelector": "खेत चयनकर्ता",
        "feedbackLoopTitle": "निर्णय प्रतिक्रिया लूप",
        "feedbackInstructions": "इस कार्रवाई को पूरा करने के लिए, कृपया भौतिक परिणाम दर्ज करें। यह लेखापरीक्षा क्षमता प्रदान करता है और भविष्य की सिफारिशों को बेहतर बनाने में मिथुन (Gemini) की मदद करता है।",
        "outcomeLabel": "अवलोकित परिणाम / कार्रवाई रिपोर्ट",
        "observationsLabel": "बाद के दृश्य अवलोकन"
    },
    "indiaIntel": {
        "title": "भारतीय कृषि खुफिया",
        "subtitle": "राष्ट्रीय और क्षेत्रीय डेटा एकत्रीकरण। फसल स्वास्थ्य रुझान, सहकारी जल तनाव चेतावनी, और सत्यापित आईसीएआर दिशानिर्देशों की खोज करें।",
        "stateLabel": "राज्य / क्षेत्र",
        "districtLabel": "जिला",
        "cropSpecLabel": "फसल विशिष्टता",
        "seasonLabel": "मौसम",
        "activeConnections": "सक्रिय नोड कनेक्शन",
        "regionalPool": "क्षेत्रीय पूल",
        "cropWaterStress": "फसल जल तनाव",
        "groundwaterDepleting": "निगरानी भूजल घट रहा है",
        "adoptionRate": "पुनर्योजी अपनाने की दर",
        "adoptionDetails": "आवरण फसल और AWD अपनाना",
        "coopAlerts": "सहकारी सामुदायिक अलर्ट",
        "coopAlertsSub": "क्षेत्रीय नोड्स के बीच साझा अंतर्दृष्टि। कीटों के प्रकोप या भूजल के अत्यधिक दोहन पर पड़ोसियों को सहकारी रूप से सचेत करता है।",
        "noAlerts": "इस क्षेत्र में कोई अलर्ट रिपोर्ट नहीं किया गया है।",
        "ragTitle": "आधिकारिक आईसीएआर ज्ञान RAG",
        "ragSubtitle": "भारतीय कृषि अनुसंधान परिषद से सत्यापित दिशानिर्देश खोजें। संदर्भ-आधारित पुनर्योजी प्रथाओं को लौटाता है।",
        "ragPlaceholder": "जैसे गेहूं बोने का समय, वैकल्पिक गीलापन और सुखाना",
        "verifiedGuideline": "सत्यापित दिशानिर्देश",
        "askQuestion": "सवाल पूछें",
        "ragPrompt": "भारत-स्तरीय गेहूं, चावल या कपास के लिए क्षेत्रीय प्रथाओं को पुनः प्राप्त करें।"
    }
}

new_keys_bn = {
    "labels": {
        "dry": "শুষ্ক",
        "decreasing": "হ্রাস পাচ্ছে",
        "locale": "ভাষা",
        "farms": "খামার"
    },
    "buttons": {
        "stopAudio": "অডিও বন্ধ করুন",
        "listenTts": "শুনুন (TTS)",
        "logAction": "পদক্ষেপ লগ করুন",
        "dismiss": "বাতিল করুন",
        "markComplete": "সম্পন্ন চিহ্নিত করুন",
        "logOutcome": "ফলাফল লগ করুন এবং বন্ধ করুন"
    },
    "states": {
        "thinking": "ভাবছি..."
    },
    "simulator": {
        "soilType": "মাটির ধরন",
        "soilClayLoam": "কাদামাটি দোআঁশ (ভার্টিসল)",
        "soilSiltLoam": "পলি দোআঁশ (সিল্ট লোম)",
        "soilSandyLoam": "বেলে দোআঁশ (স্যান্ডি লোম)",
        "rotationLabel": "৩-বছরের শস্য আবর্তন",
        "selectCrop": "শস্য নির্বাচন করুন...",
        "cropWheat": "গম (সিন্ধু-গাঙ্গেয় সমভূমি)",
        "cropRice": "ধান (জল নিবিড়)",
        "cropCotton": "তুলা (দাক্ষিণাত্য বৃষ্টিপাত নির্ভর)",
        "cropSoybean": "সয়াবিন (লেগুম নাইট্রোজেন সংস্থাপক)",
        "cropSunnhemp": "সান হেম্প (আবরণ শস্য)",
        "cropCowpea": "বরবটি (আবরণ শস্য)",
        "disclaimer": "গণনাগুলি কৃষি ইনপুটের উপর ভিত্তি করে নির্ধারিত, যেখানে কৌশলগুলি জেমিনি (Gemini) দ্বারা উত্পন্ন হয়।",
        "resultsTitle": "সিমুলেশন ফলাফল",
        "noSimulation": "এখনও পর্যন্ত কোনো সিমুলেশন নেই",
        "runPrompt": "আপনার পরামিতিগুলি প্রবেশ করুন এবং অনুমানিত ফলাফলগুলি দেখতে সিমুলেশনটি চালান।",
        "runningSimulation": "বহু-দৃশ্য সিমুলেশন চলছে...",
        "creditsYr": "ক্রেডিট/বছর",
        "chartTitle": "দৃশ্যকল্প {selectedScenario} विवरण: এসওসি এবং ক্রেডিট সঞ্চয় প্রবণতা (2026-2030)",
        "soilCarbon": "মাটির কার্বন (%)",
        "agroAnalysis": "এআই কৌশলগত শস্য-আবর্তন विश्लेषण",
        "errorSoil": "একটি মাটির ধরন নির্বাচন করুন",
        "errorAcreage": "0-এর বেশি একর পরিমাণ লিখুন",
        "errorAcreageLarge": "মানটি অনেক বড়",
        "errorYield": "একটি বৈধ ফলন লিখুন",
        "errorRotation": "প্রতিটি বছরের জন্য একটি শস্য নির্বাচন করুন"
    },
    "copilot": {
        "consoleTitle": "এআই রিজনিং কনসোল",
        "defaultInferred": "তুলার গাছগুলি গুরুত্বপূর্ণ ফুল ফোটার সময়কালে মাঝারি জলের ঘাটতির সম্মুখীন হচ্ছে, যার ফলে উদ্ভিদের ঘনত্ব হ্রাস পাচ্ছে।",
        "defaultRec1": "পশ্চিমের মাঠে ১২ মিমি সেচ চক্র চালান।",
        "defaultRec2": "শিকড়ের স্থিতিস্থাপকতা জোরদার করতে অল্টারনেট ওয়েটিং অ্যান্ড ড্রায়িং (AWD) বিবেচনা করুন।",
        "defaultRec3": "আর্দ্রতা বাড়লে জৈব ঢাল (সিউডোমোনাস ফ্লুরোসেন্স) স্প্রে করুন।",
        "groundingTitle": "সক্রিয় গ্রাউন্ডিং প্রসঙ্গ",
        "groundingSubtitle": "উত্তরগুলিকে আপনার খামারের লাইভ টেলিমেট্রিতে গ্রাউন্ড রাখতে এই প্রসঙ্গটি স্বয়ংক্রিয়ভাবে জেমিনি (Gemini) এর প্রম্পটে প্রবেশ করানো হয়।",
        "sampleInquiries": "নমুনা অনুসন্ধান:",
        "sampleInquiry1": "\"আমার তুলার এনডিভিআই কেন কমছে? আমার কী সেচের পদক্ষেপ নেওয়া দরকার?\"",
        "sampleInquiry2": "\"মহারাষ্ট্রে পিঙ্ক বলওয়ার্ম প্রতিরোধ করার জন্য বিটি তুলা চাষের কী কী পদ্ধতি আছে?\"",
        "sampleInquiry3": "\"আমি কীভাবে আমার কাদামাটি ভার্টিসল মাটিতে মাটির সংকোচন ভাঙতে পারি?\""
    },
    "actions": {
        "addCustom": "কাস্টম কাজ যোগ করুন",
        "emptyTitle": "কোনো পদক্ষেপ পাওয়া যায়নি",
        "emptySubtitle": "শুরু করতে অন্য ফিল্টার নির্বাচন করুন বা একটি কাস্টম কৃষি কাজ যোগ করুন।",
        "dueDateLabel": "নিয়ত তারিখ",
        "descriptionLabel": "সুপারিশ / পদক্ষেপের বিবরণ",
        "fieldSelector": "মাঠ নির্বাচক",
        "feedbackLoopTitle": "সিদ্ধান্তের প্রতিক্রিয়া লুপ",
        "feedbackInstructions": "এই পদক্ষেপটি সম্পূর্ণ করতে, দয়া করে প্রকৃত ফলাফলগুলি রেকর্ড করুন। এটি নিরীক্ষণ যোগ্যতা প্রদান করে এবং জেমিনিকে (Gemini) ভবিষ্যতের সুপারিশগুলি উন্নত করতে সহায়তা করে।",
        "outcomeLabel": "পর্যবেক্ষিত ফলাফল / পদক্ষেপের রিপোর্ট",
        "observationsLabel": "পরবর্তী দৃশ্যমান পর্যবেক্ষণ"
    },
    "indiaIntel": {
        "title": "ভারতীয় কৃষি বুদ্ধিমত্তা",
        "subtitle": "জাতীয় এবং আঞ্চলিক তথ্য সংগ্রহ। শস্যের স্বাস্থ্যের প্রবণতা, সমবায় জলের ঘাটতির সতর্কতা এবং যাচাইকৃত ICAR নির্দেশিকা অনুসন্ধান করুন।",
        "stateLabel": "রাজ্য / অঞ্চল",
        "districtLabel": "জেলা",
        "cropSpecLabel": "শস্য নির্দিষ্টকরণ",
        "seasonLabel": "ঋতু",
        "activeConnections": "সক্রিয় নোড সংযোগ",
        "regionalPool": "আঞ্চলিক পুল",
        "cropWaterStress": "শস্যের জলের ঘাটতি",
        "groundwaterDepleting": "পর্যবেক্ষিত ভূগর্ভস্থ জল হ্রাস পাচ্ছে",
        "adoptionRate": "পুনর্জন্মমূলক গ্রহণের হার",
        "adoptionDetails": "আবরণ শস্য এবং AWD গ্রহণ",
        "coopAlerts": "সমবায় সম্প্রদায়ের সতর্কতা",
        "coopAlertsSub": "আঞ্চলিক নোডগুলির মধ্যে ভাগ করা অন্তর্দৃষ্টি। কীটপতঙ্গের প্রাদুর্ভাব বা ভূগর্ভस्थ জলের অতিরিক্ত উত্তোলনের বিষয়ে প্রতিবেশীদের সমবায়ের মাধ্যমে সতর্ক করে।",
        "noAlerts": "এই অঞ্চলে কোনো সতর্কতা রিপোর্ট করা হয়নি।",
        "ragTitle": "আকর্ষণীয় ICAR জ্ঞান RAG",
        "ragSubtitle": "ইন্ডিয়ান কাউন্সিল অব এগ্রিকালচারাল রিসার্চ থেকে যাচাইকৃত নির্দেশিকা অনুসন্ধান করুন। প্রসঙ্গ-ভিত্তিক পুনর্জন্মমূলক অনুশীলনগুলি প্রদান করে।",
        "ragPlaceholder": "যেমন গমের বপনের সময়, বিকল্প ভেজানো এবং শুকানো",
        "verifiedGuideline": "যাচাইকৃত নির্দেশিকা",
        "askQuestion": "একটি প্রশ্ন জিজ্ঞাসা করুন",
        "ragPrompt": "ভারত-স্তরের গম, ধান বা তুলার জন্য আঞ্চলিক অনুশীলনগুলি পুনরুদ্ধার করুন।"
    }
}

new_keys_mr = {
    "labels": {
        "dry": "कोरडे",
        "decreasing": "कमी होत आहे",
        "locale": "भाषा",
        "farms": "शेत"
    },
    "buttons": {
        "stopAudio": "ऑडिओ थांबवा",
        "listenTts": "ऐका (TTS)",
        "logAction": "कृती लॉग करा",
        "dismiss": "रद्द करा",
        "markComplete": "पूर्ण म्हणून चिन्हांकित करा",
        "logOutcome": "निकाल लॉग करा आणि बंद करा"
    },
    "states": {
        "thinking": "विचार करत आहे..."
    },
    "simulator": {
        "soilType": "मातीचा प्रकार",
        "soilClayLoam": "चिकणमाती दोमट (व्हर्टिसोल)",
        "soilSiltLoam": "गाळ दोमट (सिल्ट लोम)",
        "soilSandyLoam": "वाळू मिश्रित दोमट (सँडी लोम)",
        "rotationLabel": "३-वर्षीय पीक फेरपालट",
        "selectCrop": "पीक निवडा...",
        "cropWheat": "गहू (इंडो-गंगेचे मैदान)",
        "cropRice": "भात (पाण्याची जास्त गरज)",
        "cropCotton": "कापूस (दख्खन कोरडवाहू)",
        "cropSoybean": "सोयाबीन (द्विदल नायट्रोजन स्थिर करणारे)",
        "cropSunnhemp": "ताग (ताग पीक)",
        "cropCowpea": "चवळी (आच्छादन पीक)",
        "disclaimer": "गणना कृषी इनपुटवर आधारित आहे, तर धोरणे जेमिनी (Gemini) द्वारे तयार केली जातात.",
        "resultsTitle": "सिमुलेशन निकाल",
        "noSimulation": "अद्याप सिमुलेशन नाही",
        "runPrompt": "तुमचे पॅरामीटर्स प्रविष्ट करा आणि अंदाजित परिणाम पाहण्यासाठी सिमुलेशन चालवा.",
        "runningSimulation": "बहु-परिस्थिती सिमुलेशन चालू आहे...",
        "creditsYr": "क्रेडिट/वर्ष",
        "chartTitle": "परिस्थिती {selectedScenario} तपशील: SOC आणि क्रेडिट संचय ट्रेंड (2026-2030)",
        "soilCarbon": "माती कार्बन (%)",
        "agroAnalysis": "एआय धोरणात्मक पीक-फेरपालट विश्लेषण",
        "errorSoil": "मातीचा प्रकार निवडा",
        "errorAcreage": "० पेक्षा जास्त क्षेत्र प्रविष्ट करा",
        "errorAcreageLarge": "मूल्य खूप मोठे आहे",
        "errorYield": "योग्य उत्पन्न प्रविष्ट करा",
        "errorRotation": "प्रत्येक वर्षासाठी पीक निवडा"
    },
    "copilot": {
        "consoleTitle": "एआय रिझनिंग कन्सोल",
        "defaultInferred": "कापसाची झाडे फुलोऱ्याच्या महत्त्वाच्या कालावधीत मध्यम पाण्याच्या ताणाचा सामना करत आहेत, ज्यामुळे वनस्पतींची घनता कमी होत आहे.",
        "defaultRec1": "पश्चिम शेतात १२ मिमी सिंचन चक्र चालवा.",
        "defaultRec2": "मुळांची लवचिकता मजबूत करण्यासाठी अल्टरनेट वेटिंग अँड ड्रायिंग (AWD) चा विचार करा.",
        "defaultRec3": "आर्द्रता वाढल्यास सेंद्रिय ढाल (स्युडोमोनास फ्लोरेसन्स) ची फवारणी करा.",
        "groundingTitle": "सक्रिय ग्राउंडिंग संदर्भ",
        "groundingSubtitle": "प्रतिसादांना तुमच्या शेताच्या थेट टेलिमेट्रीमध्ये ग्राउंड ठेवण्यासाठी हा संदर्भ स्वयंचलितपणे जेमिनी (Gemini) च्या प्रॉम्प्टमध्ये समाविष्ट केला जातो.",
        "sampleInquiries": "नमुना चौकशी:",
        "sampleInquiry1": "\"माझा कापूस एनडीव्हीआय का घसरत आहे? मला सिंचनाचे कोणते पाऊल उचलण्याची गरज आहे?\"",
        "sampleInquiry2": "\"महाराष्ट्रात पिंक बोलवर्म रोखण्यासाठी कोणते बीटी कापूस सराव आहेत?\"",
        "sampleInquiry3": "\"मी माझ्या चिकणमाती व्हर्टिसोल मातीमध्ये मातीचे संकुचन कसे तोडू शकतो?\""
    },
    "actions": {
        "addCustom": "सानुकूल कार्य जोडा",
        "emptyTitle": "कोणतीही कृती आढळली नाही",
        "emptySubtitle": "सुरू करण्यासाठी दुसरे फिल्टर निवडा किंवा सानुकूल कृषी कार्य जोडा.",
        "dueDateLabel": "नियत तारीख",
        "descriptionLabel": "शिफारस / कृती तपशील",
        "fieldSelector": "शेत निवडक",
        "feedbackLoopTitle": "निर्णय प्रतिसाद लूप",
        "feedbackInstructions": "ही कृती पूर्ण करण्यासाठी, कृपया प्रत्यक्ष निकाल नोंदवा. हे ऑडिट करण्याची क्षमता प्रदान करते आणि जेमिनीला भविष्यातील शिफारसी सुधारण्यास मदत करते.",
        "outcomeLabel": "निरीक्षण केलेला निकाल / कृती अहवाल",
        "observationsLabel": "पुढील दृश्य निरीक्षणे"
    },
    "indiaIntel": {
        "title": "भारतीय कृषी बुद्धिमत्ता",
        "subtitle": "राष्ट्रीय आणि प्रादेशिक डेटा एकत्रीकरण. पीक आरोग्य ट्रेंड, सहकारी जल ताण इशारे आणि सत्यापित ICAR मार्गदर्शक तत्त्वे शोधा.",
        "stateLabel": "राज्य / प्रदेश",
        "districtLabel": "जिल्हा",
        "cropSpecLabel": "पीक तपशील",
        "seasonLabel": "हंगाम",
        "activeConnections": "सक्रिय नोड कनेक्शन",
        "regionalPool": "प्रादेशिक पूल",
        "cropWaterStress": "पीक पाण्याचा ताण",
        "groundwaterDepleting": "निरीक्षण केलेले भूजल कमी होत आहे",
        "adoptionRate": "पुनरुत्पादक अवलंब दर",
        "adoptionDetails": "आच्छादन पीक आणि AWD चा अवलंब",
        "coopAlerts": "सहकारी समुदाय इशारे",
        "coopAlertsSub": "प्रादेशिक नोड्स दरम्यान सामायिक केलेली अंतर्दृष्टी. कीटकांच्या प्रादुर्भावावर किंवा भूजलाच्या अतिउपशावर शेजाऱ्यांना सहकारीपणे सतर्क करते.",
        "noAlerts": "या प्रदेशात कोणतेही इशारे नोंदवले गेले नाहीत.",
        "ragTitle": "अधिकृत ICAR ज्ञान RAG",
        "ragSubtitle": "भारतीय कृषी संशोधन परिषदेकडून सत्यापित मार्गदर्शक तत्त्वे शोधा. संदर्भ-आधारित पुनरुत्पादक पद्धती प्रदान करते.",
        "ragPlaceholder": "उदा. गव्हाची पेरणीची वेळ, पर्यायी ओले करणे आणि सुकवणे",
        "verifiedGuideline": "सत्यापित मार्गदर्शक तत्त्व",
        "askQuestion": "प्रश्न विचारा",
        "ragPrompt": "भारत-स्तरीय गहू, भात किंवा कापसासाठी प्रादेशिक पद्धती मिळवा."
    }
}

new_keys_kn = {
    "labels": {
        "dry": "ಒಣ",
        "decreasing": "ಕಡಿಮೆಯಾಗುತ್ತಿದೆ",
        "locale": "ಭಾಷೆ",
        "farms": "ಹೊಲಗಳು"
    },
    "buttons": {
        "stopAudio": "ಆಡಿಯೋ ನಿಲ್ಲಿಸಿ",
        "listenTts": "ಕೇಳಿ (TTS)",
        "logAction": "ಕ್ರಮವನ್ನು ದಾಖಲಿಸಿ",
        "dismiss": "ತೆಗೆದುಹಾಕಿ",
        "markComplete": "ಪೂರ್ಣವೆಂದು ಗುರುತಿಸಿ",
        "logOutcome": "ಫಲಿತಾಂಶ ದಾಖಲಿಸಿ ಮುಚ್ಚಿ"
    },
    "states": {
        "thinking": "ಯೋಚಿಸುತ್ತಿದೆ..."
    },
    "simulator": {
        "soilType": "ಮಣ್ಣಿನ ವಿಧ",
        "soilClayLoam": "ಜೇಡಿಮಣ್ಣು ಮರಳು ಮಿಶ್ರಿತ (ವರ್ಟಿಸೋಲ್)",
        "soilSiltLoam": "ಹೂಳು ಮಣ್ಣು (ಸಿಲ್ಟ್ ಲೋಮ್)",
        "soilSandyLoam": "ಮರಳು ಮಿಶ್ರಿತ ಮಣ್ಣು (ಸ್ಯಾಂಡಿ ಲೋಮ್)",
        "rotationLabel": "೩-ವರ್ಷದ ಬೆಳೆ ಸರದಿ",
        "selectCrop": "ಬೆಳೆ ಆಯ್ಕೆಮಾಡಿ...",
        "cropWheat": "ಗೋಧಿ (ಇಂದ್ರೋ-ಗಂಗಾ ಮೈದಾನ)",
        "cropRice": "ಭತ್ತ (ಹೆಚ್ಚು ನೀರಿನ ಅಗತ್ಯತೆ)",
        "cropCotton": "ಹತ್ತಿ (ದಕ್ಕನ್ ಮಳೆ ಆಶ್ರಿತ)",
        "cropSoybean": "ಸೋಯಾಬೀನ್ (ನೈಟ್ರೋಜನ್ ಸ್ಥಿರೀಕರಿಸುವ ಬೆಳೆ)",
        "cropSunnhemp": "ಸಣಬು (ಆಚ್ಛಾದನೆ ಬೆಳೆ)",
        "cropCowpea": "ಅಲಸಂದಿ (ಆಚ್ಛಾದನೆ ಬೆಳೆ)",
        "disclaimer": "ಲೆಕ್ಕಾಚಾರಗಳು ಕೃಷಿ ಇನ್‌ಪುಟ್‌ಗಳ ಆಧಾರದ ಮೇಲೆ ನಿರ್ಧರಿಸಲ್ಪಡುತ್ತವೆ, ಆದರೆ ಯೋಜನೆಗಳನ್ನು ಜೆಮಿನಿ (Gemini) ರಚಿಸುತ್ತದೆ.",
        "resultsTitle": "ಸಿಮ್ಯುಲೇಶನ್ ಫಲಿತಾಂಶಗಳು",
        "noSimulation": "ಇನ್ನೂ ಯಾವುದೇ ಸಿಮ್ಯುಲೇಶನ್ ಇಲ್ಲ",
        "runPrompt": "ನಿಮ್ಮ ನಿಯತಾಂಕಗಳನ್ನು ನಮೂದಿಸಿ ಮತ್ತು ಅಂದಾಜು ಫಲಿತಾಂಶಗಳನ್ನು ನೋಡಲು ಸಿಮ್ಯುಲೇಶನ್ ಚಾಲನೆ ಮಾಡಿ.",
        "runningSimulation": "ಬಹು-ಸನ್ನಿವೇಶದ ಸಿಮ್ಯುಲೇಶನ್ ಚಾಲನೆಯಲ್ಲಿದೆ...",
        "creditsYr": "ಕ್ರೆಡಿಟ್/ವರ್ಷ",
        "chartTitle": "ಸನ್ನಿವೇಶ {selectedScenario} ವಿವರಗಳು: SOC ಮತ್ತು ಕ್ರೆಡಿಟ್ ಸಂಗ್ರಹಣೆಯ ಪ್ರವೃತ್ತಿ (2026-2030)",
        "soilCarbon": "ಮಣ್ಣಿನ ಇಂಗಾಲ (%)",
        "agroAnalysis": "ಎಐ ಬೆಳೆ ಸರದಿ ಕಾರ್ಯತಂತ್ರದ ವಿಶ್ಲೇಷಣೆ",
        "errorSoil": "ಮಣ್ಣಿನ ವಿಧವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
        "errorAcreage": "೦ ಕ್ಕಿಂತ ಹೆಚ್ಚಿನ ಎಕರೆ ನಮೂದಿಸಿ",
        "errorAcreageLarge": "ಮೌಲ್ಯವು ತುಂಬಾ ದೊಡ್ಡದಾಗಿದೆ",
        "errorYield": "ಮಾನ್ಯವಾದ ಇಳುವರಿಯನ್ನು ನಮೂದಿಸಿ",
        "errorRotation": "ಪ್ರತಿ ವರ್ಷಕ್ಕೆ ಒಂದು ಬೆಳೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ"
    },
    "copilot": {
        "consoleTitle": "ಎಐ ರೀಸನಿಂಗ್ ಕನ್ಸೋಲ್",
        "defaultInferred": "ಹತ್ತಿ ಗಿಡಗಳು ಹೂಬಿಡುವ ಪ್ರಮುಖ ಹಂತದಲ್ಲಿ ಸಾಧಾರಣ ನೀರಿನ ಕೊರತೆಯನ್ನು ಎದುರಿಸುತ್ತಿವೆ, ಇದರಿಂದಾಗಿ ಸಸ್ಯಗಳ ಸಾಂದ್ರತೆಯು ಕಡಿಮೆಯಾಗುತ್ತಿದೆ.",
        "defaultRec1": "ಪಶ್ಚಿಮ ಹೊಲದಲ್ಲಿ 12 ಎಂಎಂ ನೀರಾವರಿ ಚಕ್ರವನ್ನು ಚಾಲಯಿಸಿ.",
        "defaultRec2": "ಬೇರುಗಳ ಸ್ಥಿತಿಸ್ಥಾಪಕತ್ವವನ್ನು ಬಲಪಡಿಸಲು ಪರ್ಯಾಯ ಒದ್ದೆ ಮತ್ತು ಒಣಗಿಸುವಿಕೆ (AWD) ವಿಧಾನವನ್ನು ಪರಿಗಣಿಸಿ.",
        "defaultRec3": "ಆರ್ದ್ರತೆ ಹೆಚ್ಚಾದರೆ ಸಾವಯವ ರಕ್ಷಕವನ್ನು (ಸ್ಯೂಡೋಮೊನಾಸ್ ಫ್ಲೋರೆಸೆನ್ಸ್) ಸಿಂಪಡಿಸಿ.",
        "groundingTitle": "ಸಕ್ರಿಯ ಗ್ರೌಂಡಿಂಗ್ ಸಂದರ್ಭ",
        "groundingSubtitle": "ಪ್ರತಿಕ್ರಿಯೆಗಳನ್ನು ನಿಮ್ಮ ಹೊಲದ ನೇರ ಟೆಲಿಮೆಟ್ರಿಯಲ್ಲಿ ಗ್ರೌಂಡ್ ಮಾಡಲು ಈ ಸಂದರ್ಭವನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಜೆಮಿನಿ (Gemini) ಪ್ರಾಂಪ್ಟ್‌ನಲ್ಲಿ ಇಂಜೆಕ್ಟ್ ಮಾಡಲಾಗುತ್ತದೆ.",
        "sampleInquiries": "ಮಾದರಿ ವಿಚಾರಣೆಗಳು:",
        "sampleInquiry1": "\"ನನ್ನ ಹತ್ತಿಯ ಎನ್‌ಡಿವಿಐ ಏಕೆ ಕುಸಿಯುತ್ತಿದೆ? ನನಗೆ ಯಾವ ನೀರಾವರಿ ಕ್ರಮಗಳು ಬೇಕು?\"",
        "sampleInquiry2": "\"ಮಹಾರಾಷ್ಟ್ರದಲ್ಲಿ ಪಿಂಕ್ ಬೋಲ್‌ವರ್ಮ್ ತಡೆಗಟ್ಟಲು ಯಾವ ಬಿಟಿ ಹತ್ತಿ ಪದ್ಧತಿಗಳಿವೆ?\"",
        "sampleInquiry3": "\"ನನ್ನ ಜೇಡಿ ವರ್ಟಿಸೋಲ್ ಮಣ್ಣಿನಲ್ಲಿ ಮಣ್ಣಿನ ಸಾಂದ್ರತೆಯನ್ನು ನಾನು ಹೇಗೆ ಮುರಿಯಬಹುದು?\""
    },
    "actions": {
        "addCustom": "ಕಸ್ಟಮ್ ಕಾರ್ಯ ಸೇರಿಸಿ",
        "emptyTitle": "ಯಾವುದೇ ಕ್ರಮಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
        "emptySubtitle": "ಪ್ರಾರಂಭಿಸಲು ಮತ್ತೊಂದು ಫಿಲ್ಟರ್ ಅನ್ನು ಆಯ್ಕೆಮಾಡಿ ಅಥವಾ ಕಸ್ಟಮ್ ಕೃಷಿ ಕಾರ್ಯವನ್ನು ಸೇರಿಸಿ.",
        "dueDateLabel": "ನಿಯತ ದಿನಾಂಕ",
        "descriptionLabel": "ಶಿಫಾರಸು / ಕ್ರಮದ ವಿವರಣೆ",
        "fieldSelector": "ಹೊಲ ಆಯ್ಕೆಗಾರ",
        "feedbackLoopTitle": "ನಿರ್ಧಾರದ ಪ್ರತಿಕ್ರಿಯೆ ಲೂಪ್",
        "feedbackInstructions": "ಈ ಕ್ರಮವನ್ನು ಪೂರ್ಣಗೊಳಿಸಲು, ದಯವಿಟ್ಟು ಭೌತಿಕ ಫಲಿತಾಂಶಗಳನ್ನು ದಾಖಲಿಸಿ. ಇದು ಆಡಿಟ್ ಸಾಮರ್ಥ್ಯವನ್ನು ಒದಗಿಸುತ್ತದೆ ಮತ್ತು ಭವಿಷ್ಯದ ಶಿಫಾರಸುಗಳನ್ನು ಸುಧಾರಿಸಲು ಜೆಮಿನಿಗೆ ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
        "outcomeLabel": "ವೀಕ್ಷಿಸಿದ ಫಲಿತಾಂಶ / ಕ್ರಮದ ವರದಿ",
        "observationsLabel": "ನಂತರದ ದೃಶ್ಯ ಅವಲೋಕನಗಳು"
    },
    "indiaIntel": {
        "title": "ಭಾರತೀಯ ಕೃಷಿ ಬುದ್ಧಿಮತ್ತೆ",
        "subtitle": "ರಾಷ್ಟ್ರ ಹಾಗೂ ಪ್ರಾದೇಶಿಕ ಡೇಟಾ ಕ್ರೋಢೀಕರಣ. ಬೆಳೆ ಆರೋಗ್ಯ ಪ್ರವೃತ್ತಿಗಳು, ಸಹಕಾರಿ ನೀರಿನ ಕೊರತೆಯ ಎಚ್ಚರಿಕೆಗಳು ಮತ್ತು ಪರಿಶೀಲಿಸಿದ ICAR ಮಾರ್ಗಸೂಚಿಗಳನ್ನು ಹುಡುಕಿ.",
        "stateLabel": "ರಾಜ್ಯ / ಪ್ರದೇಶ",
        "districtLabel": "ಜಿಲ್ಲೆ",
        "cropSpecLabel": "ಬೆಳೆ ವಿವರಣೆ",
        "seasonLabel": "ಋತು",
        "activeConnections": "ಸಕ್ರಿಯ ನೋಡ್ ಸಂಪರ್ಕಗಳು",
        "regionalPool": "ಪ್ರಾದೇಶಿಕ ಪೂಲ್",
        "cropWaterStress": "ಬೆಳೆ ನೀರಿನ ಕೊರತೆ",
        "groundwaterDepleting": "ಮೇಲ್ವಿಚಾರಣೆಯ ಅಂತರ್ಜಲ ಕುಸಿಯುತ್ತಿದೆ",
        "adoptionRate": "ಪುನರುತ್ಪಾದಕ ದತ್ತು ದರ",
        "adoptionDetails": "ಆಚ್ಛಾದನೆ ಬೆಳೆ ಮತ್ತು AWD ಅಳವಡಿಕೆ",
        "coopAlerts": "ಸಹಕಾರಿ ಸಮುದಾಯ ಎಚ್ಚರಿಕೆಗಳು",
        "coopAlertsSub": "ಪ್ರಾದೇಶಿಕ ನೋಡ್‌ಗಳ ನಡುವೆ ಹಂಚಿಕೊಂಡ ಒಳನೋಟಗಳು. ಕೀಟಗಳ ಬಾಧೆ ಅಥವಾ ಅಂತರ್ಜಲದ ಅತಿಯಾದ ಬಳಕೆಯ ಬಗ್ಗೆ ನೆರೆಹೊರೆಯವರಿಗೆ ಸಹಕಾರಿಯಾಗಿ ಎಚ್ಚರಿಸುತ್ತದೆ.",
        "noAlerts": "ಈ ಪ್ರದೇಶದಲ್ಲಿ ಯಾವುದೇ ಎಚ್ಚರಿಕೆಗಳು ದಾಖಲಾಗಿಲ್ಲ.",
        "ragTitle": "ಅಧಿಕೃತ ICAR ಜ್ಞಾನ RAG",
        "ragSubtitle": "ಭಾರತೀಯ ಕೃಷಿ ಸಂಶೋಧನಾ ಮಂಡಳಿಯಿಂದ ಪರಿಶೀಲಿಸಿದ ಮಾರ್ಗಸೂಚಿಗಳನ್ನು ಹುಡುಕಿ. ಸಂದರ್ಭ-ಆಧಾರಿತ ಪುನರುತ್ಪಾದಕ ಪದ್ಧತಿಗಳನ್ನು ನೀಡುತ್ತದೆ.",
        "ragPlaceholder": "ಉದಾ. ಗೋಧಿ ಬಿತ್ತನೆ ಸಮಯ, ಪರ್ಯಾಯ ಒದ್ದೆ ಮತ್ತು ಒಣಗಿಸುವಿಕೆ",
        "verifiedGuideline": "ಪರಿಶೀಲಿಸಿದ ಮಾರ್ಗಸೂಚಿ",
        "askQuestion": "ಪ್ರಶ್ನೆ ಕೇಳಿ",
        "ragPrompt": "ಭಾರತ-ಮಟ್ಟದ ಗೋಧಿ, ಭತ್ತ ಅಥವಾ ಹತ್ತಿಗೆ ಪ್ರಾದೇಶಿಕ ಪದ್ಧತಿಗಳನ್ನು ಪಡೆದುಕೊಳ್ಳಿ."
    }
}

mapping = {
    "en-IN.json": new_keys_en,
    "hi-IN.json": new_keys_hi,
    "bn-IN.json": new_keys_bn,
    "mr-IN.json": new_keys_mr,
    "kn-IN.json": new_keys_kn
}

# Process each file
for filename, keys_to_merge in mapping.items():
    filepath = os.path.join(locales_dir, filename)
    if os.path.exists(filepath):
        try:
            with open(filepath, "r", encoding="utf-8") as f:
                data = json.load(f)
            
            # Recursive deep merge
            for section, keys in keys_to_merge.items():
                if section not in data:
                    data[section] = {}
                for k, v in keys.items():
                    data[section][k] = v
            
            # Write back
            with open(filepath, "w", encoding="utf-8") as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
            print(f"Successfully updated {filename}")
        except Exception as e:
            print(f"Error updating {filename}: {e}")
    else:
        print(f"File not found: {filepath}")
